#!/usr/bin/env bash

set -x

DEVICE=$1

ls ${DEVICE}* | sudo xargs -n1 umount -l || true
nix build .#nixosConfigurations.endor.config.system.build.isoImage
ISO=./result/iso/$(ls -Art ./result/iso | tail -n 1)
sudo dd bs=4M conv=fsync oflag=direct status=progress if=${ISO} of=${DEVICE}

